/* tslint:disable */
/* eslint-disable */
/**
 * Notes AI Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatCreateResponse
 */
export interface ChatCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof ChatCreateResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ChatCreateResponse
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof ChatCreateResponse
     */
    title: string;
}

/**
 * Check if a given object implements the ChatCreateResponse interface.
 */
export function instanceOfChatCreateResponse(value: object): value is ChatCreateResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ChatCreateResponseFromJSON(json: any): ChatCreateResponse {
    return ChatCreateResponseFromJSONTyped(json, false);
}

export function ChatCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'title': json['title'],
    };
}

export function ChatCreateResponseToJSON(json: any): ChatCreateResponse {
    return ChatCreateResponseToJSONTyped(json, false);
}

export function ChatCreateResponseToJSONTyped(value?: ChatCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'title': value['title'],
    };
}

